@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v4
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Documentos
GET {{baseUrl}}/arc_documentos
X-Api-Key: {{api_key}}

### Documentos en el Distrito de Saltillo
GET {{baseUrl}}/arc_documentos
    ?distrito_clave=DSLT
X-Api-Key: {{api_key}}

### Documentos con ubicación en archivo
GET {{baseUrl}}/arc_documentos
    ?ubicacion=archivo
X-Api-Key: {{api_key}}

### Solicitudes
GET {{baseUrl}}/arc_solicitudes
X-Api-Key: {{api_key}}

### Remesas
GET {{baseUrl}}/arc_remesas
X-Api-Key: {{api_key}}

### Documentos de las Remesas
GET {{baseUrl}}/arc_remesas_documentos
X-Api-Key: {{api_key}}
