@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v4
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Centros de Trabajo
GET {{baseUrl}}/centros_trabajos
X-Api-Key: {{api_key}}

### Centros de Trabajo en el Distrito Judicial de Monclova
GET {{baseUrl}}/centros_trabajos
    ?distrito_clave=DMNC
X-Api-Key: {{api_key}}

### Centros de Trabajo en el domicilio con id 18 MERCANTILES
GET {{baseUrl}}/centros_trabajos
    ?domicilio_id=18
X-Api-Key: {{api_key}}

### Centros de Trabajo en el Distrito Judicial de Monclova
GET {{baseUrl}}/centros_trabajos
    ?distrito_clave=DMNC
X-Api-Key: {{api_key}}

### Centro de Trabajo SECRETARIA TECNICA Y DE TRANSPARENCIA
GET {{baseUrl}}/centros_trabajos/05J010901N
X-Api-Key: {{api_key}}

### Funcionarios
GET {{baseUrl}}/funcionarios
X-Api-Key: {{api_key}}

### Funcionarios en el Distrito Judicial de Rio Grande
GET {{baseUrl}}/funcionarios
    ?distrito_clave=DRGR
X-Api-Key: {{api_key}}

### Funcionarios con en_soportes en verdadero
GET {{baseUrl}}/funcionarios
    ?en_soportes=true
X-Api-Key: {{api_key}}

### Funcionario con id 705
GET {{baseUrl}}/funcionarios/705
X-Api-Key: {{api_key}}
