@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v4
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Domicilios
GET {{baseUrl}}/domicilios
    ?offset=10
X-Api-Key: {{api_key}}

### Domicilio con id 18 MERCANTILES
GET {{baseUrl}}/domicilios/18
X-Api-Key: {{api_key}}

### Oficinas
GET {{baseUrl}}/oficinas
X-Api-Key: {{api_key}}

### Oficinas en MERCANTILES
GET {{baseUrl}}/oficinas
    ?domicilio_id=18
X-Api-Key: {{api_key}}
