@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v4
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Sentencias
GET {{baseUrl}}/sentencias
X-Api-Key: {{api_key}}

### Reporte diario de Sentencias
GET {{baseUrl}}/sentencias/reporte_diario
    ?creado=2023-08-01
X-Api-Key: {{api_key}}

### Sentencias de la autoridad 37
GET {{baseUrl}}/sentencias
    ?autoridad_id=37
X-Api-Key: {{api_key}}

### Sentencias del SLT-J2-CIV
GET {{baseUrl}}/sentencias
    ?autoridad_clave=SLT-J2-CIV
X-Api-Key: {{api_key}}

### Sentencias del SLT-J2-CIV expedientes del 2019
GET {{baseUrl}}/sentencias
    ?autoridad_clave=SLT-J2-CIV
    &expediente_anio=2019
X-Api-Key: {{api_key}}

### Sentencias del SLT-J2-CIV del 2021-05-31
GET {{baseUrl}}/sentencias
    ?autoridad_clave=SLT-J2-CIV
    &fecha=2021-05-31
X-Api-Key: {{api_key}}

### Sentencia con id 21388
GET {{baseUrl}}/sentencias/21388
X-Api-Key: {{api_key}}
