@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v4
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Grabaciones
GET {{baseUrl}}/siga_grabaciones
X-Api-Key: {{api_key}}

### Grabacion con id 5
GET {{baseUrl}}/siga_grabaciones/5
X-Api-Key: {{api_key}}

### Crear una nueva grabacion
POST {{baseUrl}}/siga_grabaciones
X-Api-Key: {{api_key}}
Content-Type: application/json

{
    "autoridad_clave": "SLT-J1-PEN",
    "siga_sala_clave": "S-SLT-CJP-01",
    "materia_clave": "PEN",
    "expediente": "2023/123",
    "inicio": "2023-06-01T10:00:00",
    "termino": "2023-06-01T11:00:00",
    "archivo_nombre": "prueba",
    "justicia_ruta": "/mnt/respaldos/siga/sala00/prueba.mp4",
    "tamanio": 1024000,
    "duracion": "01:00:00",
    "estado": "VALIDO"
}
